Build BSP is only optional, and not even required for the Simulation
MicroEJ/Tool-Project-Template-VEEPort pull request #17
Opened 2024-12-20 13:37 UTC by nhouze-microej

2024-12-20 14:01 UTC, tdelhomenie-microej requested changes

2024-12-20 14:01 UTC, tdelhomenie-microej commented on README.md
> +
Shouldn't we add a note in the `BSP Compilation` section to add the `Run an Application on the Device` step as a requirement to compile the BSP? It would make it clear that the BSP cannot be compile if this step is not done before.

2024-12-20 14:01 UTC, tdelhomenie-microej commented on README.md
> +To build and run the Application on the Device, the BSP are C/C++ Toolchain are required.
```suggestion
To build and run the Application on the Device, the BSP and C/C++ Toolchain are required.
```

2024-12-20 14:01 UTC, tdelhomenie-microej commented on README.md
> +Before continuing further, please refer to the [BSP Setup](#bsp-setup) section below to setup the toolchain.
All "please" occurrences should be removed.

2024-12-20 14:40 UTC, nhouze-microej commented on README.md
> +
I reorder more things...

Now the toolchain setup goes before `runOnDevice`.

And the BSP Compilation section is there to to show how build the BSP without rebuilding the app. it is more explicit

A little bit like "Deploying the Executable without building it" in https://docs.microej.com/en/latest/SDK6UserGuide/runOnDevice.html

2025-01-06 10:26 UTC, tdelhomenie-microej approved these changes

2025-01-06 13:01 UTC, jcourcelmicroej approved these changes

2025-01-06 15:15 UTC, merged